spring:
  application:
    name: PaymentService

  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:payment_service_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

springdoc:
  swagger-ui:
    path: /api-docs

server:
  port: ${SERVER_PORT:8083}

logging:
  level:
    org.springframework.r2dbc.connection: DEBUG
    io.r2dbc.postgresql: DEBUG
